# Generated by Django 4.2.1 on 2023-05-13 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network_operator', '0002_alter_networkoperators_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('iccid', models.CharField(max_length=50, verbose_name='Integrated Circuit Card ID (ICCID)')),
                ('msisdn', models.CharField(max_length=20, unique=True, verbose_name='Mobile Station ISDN Number (MSISDN)')),
                ('imsi', models.CharField(max_length=20, unique=True, verbose_name='International Mobile Subscriber Identity (IMSI)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='networkoperators',
            name='country',
            field=django_countries.fields.CountryField(default='BD', max_length=2),
        ),
        migrations.AlterField(
            model_name='networkoperators',
            name='mcc',
            field=models.PositiveIntegerField(verbose_name='Mobile Country Codes (MCC)'),
        ),
        migrations.AlterField(
            model_name='networkoperators',
            name='mnc',
            field=models.PositiveIntegerField(verbose_name='Mobile Network Codes (MNC)'),
        ),
        migrations.CreateModel(
            name='ConsumerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('mno_profiles', models.ManyToManyField(blank=True, related_name='consumer_profile', to='network_operator.communicationprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='communicationprofile',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_mno', to='network_operator.networkoperators'),
        ),
    ]
