# Generated by Django 4.2.1 on 2023-05-13 17:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network_operator', '0003_communicationprofile_networkoperators_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerkyc',
            name='country',
            field=django_countries.fields.CountryField(default='BD', max_length=2),
        ),
    ]
