# Generated by Django 4.2.1 on 2023-05-13 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network_operator', '0004_consumerkyc_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerkyc',
            old_name='country',
            new_name='nationality',
        ),
        migrations.AddField(
            model_name='communicationprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumerkyc',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consumerkyc',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerkyc',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name"),
        ),
        migrations.CreateModel(
            name='RoamingPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pack_name', models.CharField(max_length=100)),
                ('offer_details', models.TextField(max_length=500)),
                ('tariff_excluding', models.FloatField(verbose_name='Tariff (Excluding VAT, SD, and SC)')),
                ('tariff_inclusive', models.FloatField(verbose_name='Tariff (All Inclusive)')),
                ('currency', models.CharField(choices=[('bdt', 'BDT'), ('usd', 'USD'), ('eur', 'EUR')], default='usd', max_length=20)),
                ('service_duration', models.FloatField(verbose_name='Duration in hours')),
                ('ussd_code', models.CharField(max_length=10, verbose_name='USSD Code')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roaming_mno', to='network_operator.networkoperators')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roaming_pmno', to='network_operator.networkoperators')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
