# Generated by Django 4.2.1 on 2023-05-14 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network_operator', '0005_rename_country_consumerkyc_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerkyc',
            name='shareable_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
