# Generated by Django 4.2.1 on 2023-05-11 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContractDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=42)),
                ('artifact_abi', models.JSONField()),
                ('deployer', models.CharField(max_length=42)),
                ('network', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignTypeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('domain_name', models.CharField(max_length=100)),
                ('domain_version', models.PositiveIntegerField()),
                ('chain_id', models.PositiveIntegerField()),
                ('sign_type_version', models.CharField(default='eth_signTypedData_v4', max_length=30)),
                ('smart_contract_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_contract', to='public_blockchain_manager.smartcontractdeployment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EthSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('signer_address', models.CharField(max_length=42)),
                ('signature', models.CharField(blank=True, max_length=132, null=True)),
                ('message', models.JSONField()),
                ('status', models.BooleanField(choices=[(True, 'Accept'), (False, 'Reject')])),
                ('sign_domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_domain', to='public_blockchain_manager.signtypedata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
