# Generated by Django 4.2.1 on 2023-05-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_blockchain_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethsignature',
            old_name='sign_domain_id',
            new_name='sign_domain',
        ),
    ]
