# Generated by Django 4.2.1 on 2023-05-12 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticdetail',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('chassis_type', models.CharField(choices=[('sedan', 'Sedan'), ('minivan', 'Minivan-MPV'), ('hatchback', 'Hatchback-MPV'), ('pickup', 'Pickup'), ('freezer_van', 'Freezer Van'), ('covered_van', 'Covered Van'), ('truck', 'Truck')], default='minivan', max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('capacity_unit', models.CharField(choices=[('kg', 'KG'), ('ton', 'TON')], default='ton', max_length=10)),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_owner', to='logistics.logisticdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=200, unique=True)),
                ('national_id', models.CharField(max_length=200, unique=True)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(choices=[('a_pos', 'A+'), ('a_neg', 'A-'), ('b_pos', 'B+'), ('b_neg', 'B-'), ('ab_pos', 'AB+'), ('ab_neg', 'AB-'), ('o_pos', 'O+'), ('o_neg', 'O-')], max_length=10)),
                ('issuer_authority', models.CharField(max_length=200)),
                ('issue_year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)])),
                ('validity_date', models.DateField()),
                ('duty_vehicle', models.ManyToManyField(blank=True, null=True, related_name='driver_vehicle', to='logistics.transportdetail')),
                ('employer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_employer', to='logistics.logisticdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
