# Generated by Django 4.2.1 on 2023-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_logisticdetail_address_transportdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='authority_zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='registration_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
