# Generated by Django 4.2.1 on 2023-05-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_transportdetail_authority_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetail',
            name='duty_vehicle',
        ),
        migrations.RemoveField(
            model_name='transportdetail',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='owners_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='transport_owners', to='logistics.logisticdetail'),
        ),
    ]
