# Generated by Django 4.2.1 on 2023-05-13 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_driverdetail_duty_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_batch_id', models.UUIDField(blank=True, null=True)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_weight', models.PositiveIntegerField()),
                ('weight_unit', models.CharField(choices=[('kg', 'KG'), ('ton', 'TON')], default='kg', max_length=10)),
                ('chassis_type', models.CharField(choices=[('sedan', 'Sedan'), ('minivan', 'Minivan-MPV'), ('hatchback', 'Hatchback-MPV'), ('pickup', 'Pickup'), ('freezer_van', 'Freezer Van'), ('covered_van', 'Covered Van'), ('truck', 'Truck')], default='minivan', max_length=20)),
                ('sender_contact', models.CharField(max_length=15)),
                ('from_address', models.TextField(max_length=500)),
                ('from_country', django_countries.fields.CountryField(max_length=2)),
                ('receiver_contact', models.CharField(max_length=15)),
                ('to_address', models.TextField(max_length=500)),
                ('to_country', django_countries.fields.CountryField(max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('pick_up', 'Pick Up'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_logistics', to='logistics.logisticdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_cost', models.PositiveIntegerField()),
                ('trx_id', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(choices=[('eth', 'ETH'), ('matic', 'Matic'), ('fiat', 'FIAT')], default='fiat', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_driver', to='logistics.driverdetail')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_transport', to='logistics.transportdetail')),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_booking', to='logistics.deliverybooking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
