# Generated by Django 4.2.1 on 2023-05-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_deliverybooking_deliveryinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybooking',
            name='remark',
            field=models.CharField(default='Client nick name', max_length=100),
        ),
    ]
