# Generated by Django 4.2.1 on 2023-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_deliverybooking_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinvoice',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='driverdetail',
            old_name='employer_id',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='transportdetail',
            old_name='owners_id',
            new_name='owners',
        ),
        migrations.AlterField(
            model_name='deliverybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('pick_up', 'Pick Up'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
