# Generated by Django 4.2.1 on 2023-05-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_remove_driverdetail_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetail',
            name='is_contact_valid',
        ),
        migrations.AddField(
            model_name='driverdetail',
            name='contact_kyc',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
