# Generated by Django 4.2.1 on 2023-05-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_remove_driverdetail_is_contact_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetail',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
