import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to eSIM Dapp
        </h1>

        <p className={styles.description}>
          Global eSIM DAO and IoT ownership manaement in{' '}
          <code className={styles.code}>Blockchain</code>
        </p>

        <div className={styles.grid}>
          <button className={styles.card}>
            <h2>Connect Wallet &rarr;</h2>
            <p>Get Connected with your MetaMask Wallet.</p>
          </button>

          <a href="#" className={styles.card}>
            <h2>Add Organization &rarr;</h2>
            <p>Add new Organizations for operating in the DAO system</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>MNO Profile &rarr;</h2>
            <p>Discover and deploy new Mobile-Network-Operator and MNO Communication Profiles.</p>
          </a>

          <a
            href="https://www.gsma.com/"
            className={styles.card}
          >
            <h2>GSMA &rarr;</h2>
            <p>
              Representing the worldwide mobile communications industry.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/bs23.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
